This notebook allows the user to select XML collections and zip them up to send to a service that runs a transform on them and returns a simple CSV made up of six data points. The data included is the Collection name, Dialect name, Record name, Concept name, Content, Xpath location, and the Dialect Definition for the concept. 

The notebook utilizes Bash and Python with the default packages contained in the Mac build of Anaconda with Python 3.6. 

Saxon, Java, and XSLT form the evaluation web service on a NCEAS virtual machine. 

This CSV contains a row for each concept that is found, so some elements may fulfill multiple concepts. A good example of this are the concepts Keyword and Place Keyword. Every Place Keyword is also a Keyword, so the row would repeat with a different Concept name. It also contains a row for each undefined node that contains text, marking these rows with an Unknown in the Concept column. 

This data can be used in a variety of analyses including RAD and QuickE as well as Concept Verticals. It can also be used to teach the system dialect definitions for concepts that are currently unknown by exposing all of the content at undefined nodes.

## First we need to call all of the libraries we need to perform in our metadata wrangle

In [23]:
import pandas as pd
pd.options.display.width = 180
#import os
from os import walk
import shutil
import ipywidgets as widgets
from ipywidgets import *
import requests
import csv
import io

### Now let's select some metadata.

If you have prepared metadata\* on your computer that you want to add, it is possible to upload into the repository locally using the [Add Metadata](00AddMetadata.ipynb) Notebook before completing the following cells in this notebook. Otherwise, follow along and use some of the sample metadata the following steps will help you to select.

\* Prepared metadata contains a root element that has a standardized namespace and namespace prefix. Many dialects such as ISO and DIF are consistently written this way, but some dialects such as CSDGM are often written by organizations as only well-formed XML.

Create a list of subdirectories in the collection directory of MILE2 to select metadata for evaluation

In [24]:
Organizations = []
for (dirpath, dirnames, filenames) in walk('../collection/'):
    Organizations.extend(dirnames)
    break

Create a function to select the organization the metadata comes from

In [25]:
def OrganizationChoices(organization):
    global OrganizationChoice
    global Organization
    Organization=organization
    print("Organization of the collection is", Organization)

Create a dropdown using the Organizations list and the organization selector function. This sets the Organization variable.

In [26]:
interactive(OrganizationChoices, organization=Organizations)

Create a list of collections in the organization directory selected in the dropdown above

In [27]:
Collections = []
for (dirpath, dirnames, filenames) in walk(os.path.join('../collection',Organization)):
    Collections.extend(dirnames)
    break 
Collections

['GeoTraces']

Create a function to select the collection the metadata comes from

In [28]:
def CollectionChoices(collection):
    global CollectionChoice
    global Collection
    Collection=collection

Create a dropdown using the Collections list and the organization selector function. This sets the Collection variable.

In [29]:
interactive(CollectionChoices, collection=Collections)

Many organizations support multiple metadata dialects, and share their collections in more than one dialect. This list is created the same way the others are. It adds the different dialects the collection is shared in to a list.

In [30]:
Dialects = []
for (dirpath, dirnames, filenames) in walk(os.path.join('../collection',Organization,Collection)):
    Dialects.extend(dirnames)
    break 
dialectList=Dialects

Create a function to select the dialect you want to send to the evaluator service.

In [31]:
def dialectChoice(dialect):
    global Dialect
    Dialect=dialect
    print("Dialect of the collection is", Dialect)

Create a dropdown using the Dialects list and the dialect selector function. This sets the Dialect variable.

In [32]:
interactive(dialectChoice,dialect=dialectList)

change to the zip directory

In [33]:
cd ../zip

/Users/scgordon/MILE2/zip

Combine the Organization, Collection, and Dialect variables with the string 'xml' as a relative path and save the string to a variable

In [34]:
MetadataDestination=os.path.join(Organization,Collection,Dialect,'xml')
MetadataDestination

'BCO-DMO/GeoTraces/ISO/xml'

Use the path to create a directory structure in the zip directory

In [35]:
os.makedirs(MetadataDestination, exist_ok=True)

Create a path to the metadata you selected earlier and save the string to a variable, 'MetadataLocation'.

In [36]:
MetadataLocation=os.path.join('../collection/',Organization,Collection,Dialect,'xml')

MetadataLocation

'../collection/BCO-DMO/GeoTraces/ISO/xml'

Copy the metadata to the new directory structure.

In [37]:
src_files = os.listdir(MetadataLocation)
for file_name in src_files:
    full_file_name = os.path.join(MetadataLocation, file_name)
    if (os.path.isfile(full_file_name)):
        shutil.copy(full_file_name, MetadataDestination)

Make a zip file to upload to the evaluator service

In [38]:
shutil.make_archive('../upload/metadata', 'zip', os.getcwd())

'/Users/scgordon/MILE2/upload/metadata.zip'

In [39]:
%cd ../upload

/Users/scgordon/MILE2/upload

Send metadata to the Evaluator. Get the responses with csv encoding. This step can take up to a minute and doesn't track progress, but a dataframe or an error message will be returned.

Save the dataframe as a csv for further analysis. Copy the csv to a directory, named for the organization that had the metadata in it's holdings. Give it a filename matching the the metadata collection and dialect.

Clear up temporary files and directories, switch to the data directory

In [40]:
# Send metadata package, read the response into a dataframe
url = 'http://metadig.nceas.ucsb.edu/metadata/evaluator'
files = {'zipxml': open('metadata.zip', 'rb')}
r = requests.post(url, files=files, headers={"Accept-Encoding": "gzip"})
r.raise_for_status()
EvaluatedMetadataDF = pd.read_csv(io.StringIO(r.text), quotechar='"')

#build filepaths and file names
Filedirectory=os.path.join('../data/',Organization)
Filename='/'+Collection+'_'+Dialect+'_Evaluated.csv.gz'
SimplfiedFilename='/'+Collection+'_'+Dialect+'_EvaluatedSimplified.csv.gz'
FilePath=Filedirectory+Filename
SimplifiedFilePath=Filedirectory+SimplfiedFilename

EvaluatedMetadataDF.to_csv(FilePath, mode = 'w', compression='gzip', index=False)

#Change directories, delete upload directory and zip. Delete copied metadata.
%cd ../
shutil.rmtree('upload')
%cd zip
shutil.rmtree(Organization)
%cd ../data

#Create a simplified XPath output
EvaluatedSimplifiedMetadataDF = EvaluatedMetadataDF.copy()
EvaluatedSimplifiedMetadataDF['XPath']=EvaluatedSimplifiedMetadataDF['XPath'].str.replace('/gco:CharacterString', '')
EvaluatedSimplifiedMetadataDF['XPath']=EvaluatedSimplifiedMetadataDF['XPath'].str.replace('/[a-z]+:+?', '/')
EvaluatedSimplifiedMetadataDF['XPath']=EvaluatedSimplifiedMetadataDF['XPath'].str.replace('/[A-Z]+_[A-Za-z]+/?', '/')
EvaluatedSimplifiedMetadataDF['XPath']=EvaluatedSimplifiedMetadataDF['XPath'].str.replace('//', '/')
EvaluatedSimplifiedMetadataDF['XPath']=EvaluatedSimplifiedMetadataDF['XPath'].str.rstrip('//')
EvaluatedSimplifiedMetadataDF.to_csv(SimplifiedFilePath, mode = 'w', compression='gzip', index=False)

/Users/scgordon/MILE2
/Users/scgordon/MILE2/zip
/Users/scgordon/MILE2/data

Now that we have our metadata raw data prepared and stored, we can prepare the collection's data for recommendation analytics and cross collection analytics.

Create a table with each record as a row of concept occurance counts. Each concept that occurs in the collection is a row.

In [46]:
FiledirectoryRAD=os.path.join('../data/',Organization)
FilenameRAD='/'+Collection+'_'+Dialect+'_RAD.csv'
FilePathRAD=FiledirectoryRAD+FilenameRAD
group_name = EvaluatedSimplifiedMetadataDF.groupby(['Record', 'Concept'], as_index=False)
occuranceMatrix=group_name.size().unstack().reset_index()
occuranceMatrix=occuranceMatrix.fillna(0)
pd.options.display.float_format = '{:,.0f}'.format
occuranceMatrix.to_csv(FilePathRAD, mode = 'w', index=False)
occuranceMatrix

Concept,Record,Abstract,Acknowledgement,Address,AssociatedDIFs,Association,Attribute Definition,Attribute Label,Author / Originator,Bounding Box,...,Start Time,Temporal Extent,Theme Keyword,Topic Category,URL,Units,Unknown,VariableType,Web Page,Westernmost Longitude
0,dataset_3470.xml,1,2,5,2,2,17,17,1,1,...,0,1,15,1,1,17,477,1,7,1
1,dataset_3484.xml,1,2,5,2,2,5,5,1,1,...,0,1,6,1,1,5,352,1,7,1
2,dataset_3485.xml,1,2,5,2,2,14,14,1,1,...,0,1,14,1,1,14,429,1,7,1
3,dataset_3486.xml,1,2,5,2,2,16,16,1,1,...,0,1,15,1,1,16,455,1,7,1
4,dataset_3508.xml,1,2,5,2,2,10,10,1,1,...,0,1,10,1,1,10,398,1,7,1
5,dataset_3510.xml,1,2,5,2,2,11,11,1,1,...,0,1,11,1,1,11,408,1,7,1
6,dataset_3513.xml,1,2,5,2,2,11,11,1,1,...,0,1,10,1,1,11,395,1,7,1
7,dataset_3514.xml,1,2,5,2,2,10,10,1,1,...,0,1,9,1,1,10,385,1,7,1
8,dataset_3515.xml,1,2,5,2,2,11,11,1,1,...,0,1,10,1,1,11,395,1,7,1
9,dataset_3516.xml,1,2,5,2,2,27,27,1,1,...,0,1,24,1,1,27,584,1,7,1
10,dataset_3517.xml,1,2,5,2,2,248,249,1,1,...,0,1,91,1,1,249,"1,992",1,7,1
11,dataset_3518.xml,1,2,5,2,2,29,29,1,1,...,0,1,26,1,1,29,605,1,7,1
12,dataset_3519.xml,1,2,5,2,2,169,169,1,1,...,0,1,90,1,1,169,"1,523",1,7,1
13,dataset_3520.xml,1,2,5,2,2,14,14,1,1,...,0,1,17,1,1,14,464,1,7,1
14,dataset_3521.xml,1,2,5,2,2,22,22,1,1,...,0,1,21,1,1,22,537,1,7,1
15,dataset_3659.xml,1,2,5,2,2,17,17,1,1,...,0,1,17,1,1,17,464,1,7,1
16,dataset_3662.xml,1,2,5,2,2,174,174,1,1,...,0,1,91,1,1,174,"1,535",1,7,1
17,dataset_3664.xml,1,2,5,2,2,15,15,1,1,...,0,1,17,1,1,15,472,1,7,1
18,dataset_3671.xml,1,2,5,2,2,12,12,1,1,...,0,1,12,1,1,12,417,1,7,1
19,dataset_3672.xml,1,2,5,2,2,12,12,1,1,...,0,1,11,1,1,12,404,1,7,1
20,dataset_3673.xml,1,2,5,2,2,12,12,1,1,...,0,1,12,1,1,12,417,1,7,1
21,dataset_3674.xml,1,2,5,2,2,12,12,1,1,...,0,1,11,1,1,12,404,1,7,1
22,dataset_3687.xml,1,2,5,2,2,269,270,1,0,...,0,1,268,1,1,270,"2,246",1,7,0
23,dataset_3692.xml,1,1,5,2,2,40,40,1,1,...,0,1,37,1,1,40,725,1,8,1
24,dataset_3696.xml,1,2,5,2,2,5,5,1,1,...,0,1,6,1,1,5,344,1,7,1
25,dataset_3698.xml,1,2,5,2,2,27,27,1,1,...,0,1,25,1,1,27,588,1,7,1
26,dataset_3699.xml,1,2,5,2,2,27,27,1,1,...,0,1,27,1,1,27,607,1,7,1
27,dataset_3746.xml,1,2,5,2,2,12,12,1,1,...,0,1,12,1,1,12,417,1,7,1
28,dataset_3821.xml,1,1,5,2,2,20,20,1,1,...,0,1,21,1,1,20,525,1,7,1
29,dataset_3822.xml,1,2,5,2,2,21,21,1,1,...,0,1,20,1,1,21,528,1,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,dataset_549122.xml,1,1,5,2,2,34,34,1,1,...,1,1,23,2,1,34,622,1,8,1
88,dataset_558538.xml,1,2,5,2,2,42,42,1,1,...,0,1,37,1,1,42,760,1,7,1
89,dataset_637784.xml,1,2,5,3,3,17,17,1,0,...,0,1,17,1,1,17,508,1,9,0
90,dataset_639016.xml,1,0,5,2,2,25,29,1,1,...,0,1,19,1,1,29,575,1,7,1
91,dataset_639847.xml,1,3,6,4,4,71,88,2,0,...,0,1,51,1,1,88,951,1,9,0
92,dataset_641044.xml,1,1,5,3,3,23,31,1,1,...,1,1,15,1,1,31,555,1,8,1
93,dataset_642974.xml,1,1,5,3,3,31,31,1,0,...,0,1,19,1,1,31,584,1,8,0
94,dataset_643213.xml,1,2,5,3,3,39,39,1,0,...,0,1,28,1,1,39,658,1,8,0
95,dataset_643270.xml,1,1,5,3,3,33,33,1,1,...,1,1,23,1,1,33,591,1,8,1
96,dataset_643316.xml,1,2,5,3,3,23,23,1,0,...,0,1,20,1,1,23,530,1,8,0
97,dataset_643423.xml,1,1,5,3,3,39,39,1,0,...,0,1,13,1,1,39,593,1,8,0
98,dataset_643494.xml,1,2,5,3,3,28,35,1,0,...,0,1,17,1,1,35,598,1,8,0
99,dataset_643578.xml,1,2,5,3,3,14,15,1,0,...,0,1,13,1,1,15,463,1,8,0
100,dataset_643592.xml,1,2,5,3,3,31,31,1,0,...,0,1,22,1,1,31,598,1,8,0
101,dataset_643639.xml,1,1,5,3,3,38,50,1,1,...,0,1,22,1,1,50,710,1,8,1
102,dataset_643809.xml,1,1,5,3,3,33,33,1,1,...,0,1,18,1,1,33,592,1,8,1
103,dataset_644607.xml,1,1,5,3,3,36,36,1,0,...,0,1,24,1,1,36,633,1,8,0
104,dataset_644765.xml,1,1,5,2,2,24,24,1,0,...,0,1,23,1,0,24,551,1,8,0
105,dataset_646143.xml,1,1,5,3,3,18,18,1,0,...,1,1,18,1,1,18,488,1,8,0
106,dataset_646842.xml,1,1,5,2,2,20,20,1,0,...,0,1,16,1,1,20,488,1,7,0
107,dataset_647580.xml,1,1,5,3,3,22,22,1,0,...,1,1,18,1,1,22,530,1,8,0
108,dataset_647606.xml,1,1,5,3,3,26,26,1,0,...,1,1,20,1,1,26,570,1,8,0
109,dataset_647909.xml,1,1,5,3,3,14,14,1,0,...,1,1,14,1,1,14,458,1,8,0
110,dataset_648030.xml,1,1,5,3,3,22,26,1,0,...,1,1,14,1,1,26,526,1,8,0
111,dataset_648543.xml,1,3,6,4,4,71,88,2,0,...,0,1,53,1,1,88,967,1,9,0
112,dataset_648753.xml,1,1,5,3,3,29,29,1,0,...,0,1,18,1,1,29,567,1,8,0
113,dataset_650087.xml,1,1,5,3,3,26,26,1,0,...,0,1,19,1,1,26,545,1,8,0
114,dataset_650135.xml,1,0,5,2,2,30,30,1,1,...,0,1,21,1,1,30,552,1,7,1
115,dataset_650340.xml,1,1,5,3,3,21,21,1,0,...,0,1,18,1,1,21,513,1,8,0
116,dataset_651138.xml,1,2,5,3,3,42,42,1,0,...,0,1,16,1,1,42,661,1,9,0

In [47]:
FiledirectoryQuickE=os.path.join('../data/',Organization)
FilenameQuickE='/'+Collection+'_'+Dialect+'_QuickE.csv'
FilePathQuickE=FiledirectoryQuickE+FilenameQuickE
group_name = EvaluatedSimplifiedMetadataDF.groupby(['XPath', 'Record'], as_index=False)
QuickEdf=group_name.size().unstack().reset_index()
QuickEdf=QuickEdf.fillna(0)
pd.options.display.float_format = '{:,.0f}'.format
QuickEdf.to_csv(FilePathQuickE, mode = 'w', index=False)
QuickEdf

Record,XPath,dataset_3470.xml,dataset_3484.xml,dataset_3485.xml,dataset_3486.xml,dataset_3508.xml,dataset_3510.xml,dataset_3513.xml,dataset_3514.xml,dataset_3515.xml,...,dataset_647580.xml,dataset_647606.xml,dataset_647909.xml,dataset_648030.xml,dataset_648543.xml,dataset_648753.xml,dataset_650087.xml,dataset_650135.xml,dataset_650340.xml,dataset_651138.xml
0,/@xsi:schemaLocation,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,/acquisitionInformation/instrument,1,1,0,0,1,1,0,0,0,...,4,6,3,3,3,3,2,0,2,3
2,/acquisitionInformation/instrument/description,1,1,0,0,1,1,0,0,0,...,4,6,3,3,3,3,2,0,2,3
3,/acquisitionInformation/instrument/identifier/...,2,2,0,0,2,2,0,0,0,...,8,12,6,6,6,2,4,0,4,6
4,/acquisitionInformation/instrument/identifier/...,1,1,0,0,1,1,0,0,0,...,4,5,3,3,3,0,2,0,2,3
5,/acquisitionInformation/instrument/identifier/...,1,1,0,0,1,1,0,0,0,...,1,1,1,1,1,1,1,0,1,1
6,/acquisitionInformation/instrument/identifier/...,1,1,0,0,1,1,0,0,0,...,4,6,3,3,3,3,2,0,2,3
7,/acquisitionInformation/instrument/identifier/...,1,1,0,0,1,1,0,0,0,...,4,6,3,3,3,3,2,0,2,3
8,/acquisitionInformation/instrument/type,2,2,0,0,2,2,0,0,0,...,8,11,6,6,6,1,4,0,4,6
9,/acquisitionInformation/operation/description,2,2,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,3
10,/acquisitionInformation/operation/identifier/code,2,2,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,3
11,/acquisitionInformation/operation/identifier/c...,2,2,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,3
12,/acquisitionInformation/operation/identifier/c...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
13,/acquisitionInformation/operation/identifier/c...,2,2,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,3
14,/acquisitionInformation/operation/identifier/c...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
15,/acquisitionInformation/operation/parentOperat...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
16,/acquisitionInformation/operation/plan/citatio...,2,2,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,3
17,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,2
18,/acquisitionInformation/operation/plan/citatio...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,4
19,/acquisitionInformation/operation/plan/citatio...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,4
20,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,2
21,/acquisitionInformation/operation/plan/citatio...,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,8
22,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,2
23,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
24,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,2
25,/acquisitionInformation/operation/plan/citatio...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,4
26,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,2
27,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
28,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,2
29,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,/metadataMaintenance/contact/contactInfo,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
329,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
330,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
331,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
332,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
333,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
334,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
335,/metadataMaintenance/contact/contactInfo/conta...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
336,/metadataMaintenance/contact/contactInfo/hours...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
337,/metadataMaintenance/contact/contactInfo/onlin...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
338,/metadataMaintenance/contact/contactInfo/onlin...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
339,/metadataMaintenance/contact/contactInfo/phone...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
340,/metadataMaintenance/contact/contactInfo/phone...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
341,/metadataMaintenance/contact/organisationName,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
342,/metadataMaintenance/contact/organisationName/...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
343,/metadataMaintenance/contact/organisationName/...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
344,/metadataMaintenance/contact/organisationName/...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
345,/metadataMaintenance/contact/role,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
346,/metadataMaintenance/contact/role/@codeList,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
347,/metadataMaintenance/contact/role/@codeListValue,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
348,/metadataMaintenance/contact/role/@codeSpace,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
349,/metadataMaintenance/maintenanceAndUpdateFrequ...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
350,/metadataMaintenance/maintenanceAndUpdateFrequ...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
351,/metadataMaintenance/maintenanceAndUpdateFrequ...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
352,/metadataMaintenance/maintenanceAndUpdateFrequ...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
353,/metadataMaintenance/maintenanceNote,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
354,/metadataStandardName,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
355,/metadataStandardVersion,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
356,/referenceSystemInfo/@xlink:href,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
357,/referenceSystemInfo/@xlink:title,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [49]:
FiledirectoryOccurance=os.path.join('../data/',Organization)
FilenameOccurance='/'+Collection+'_'+Dialect+'_Occurance.csv'
FilePathOccurance=FiledirectoryOccurance+FilenameOccurance
occuranceSum=occuranceMatrix.sum()
occuranceCount=occuranceMatrix[occuranceMatrix!=0].count()
CollectionName=FilenameOccurance.partition("/")[2].partition("_Occurance.csv")[0]
result = pd.concat([occuranceSum, occuranceCount], axis=1).reset_index()
result.insert(1, 'Collection', CollectionName)
result.insert(4, 'CollectionOccurance%', CollectionName)
result.insert(4, 'AverageOccurancePerRecord', CollectionName)
result.columns = ['Concept', 'Collection', 'ConceptCount', 'RecordCount', 'AverageOccurancePerRecord', 'CollectionOccurance%' ]
NumberOfRecords = result.at[0, 'ConceptCount'].count('.xml')
result['CollectionOccurance%'] = result['RecordCount']/NumberOfRecords
result['CollectionOccurance%'] = pd.Series(["{0:.2f}%".format(val * 100) for val in result['CollectionOccurance%']], index = result.index)
result.at[0, 'ConceptCount'] = NumberOfRecords
result.at[0, 'Concept'] = 'Number of Records'
result['AverageOccurancePerRecord'] = result['ConceptCount']/NumberOfRecords
result['AverageOccurancePerRecord'] = result['AverageOccurancePerRecord'].astype(float)
result[["ConceptCount","RecordCount"]] = result[["ConceptCount","RecordCount"]].astype(int)
result['AverageOccurancePerRecord'] = pd.Series(["{0:.2f}".format(val) for val in result['AverageOccurancePerRecord']], index = result.index)
result.to_csv(FilePathOccurance, mode = 'w', index=False)
result

                                       Concept     Collection  ConceptCount  RecordCount AverageOccurancePerRecord CollectionOccurance%
0                            Number of Records  GeoTraces_ISO           117          117                      1.00              100.00%
1                                     Abstract  GeoTraces_ISO           117          117                      1.00              100.00%
2                              Acknowledgement  GeoTraces_ISO           191          115                      1.63               98.29%
3                                      Address  GeoTraces_ISO           592          117                      5.06              100.00%
4                               AssociatedDIFs  GeoTraces_ISO           261          117                      2.23              100.00%
5                                  Association  GeoTraces_ISO           261          117                      2.23              100.00%
6                         Attribute Definition  GeoTraces_ISO          4132          117                     35.32              100.00%
7                              Attribute Label  GeoTraces_ISO          4385          117                     37.48              100.00%
8                          Author / Originator  GeoTraces_ISO           125          117                      1.07              100.00%
9                                 Bounding Box  GeoTraces_ISO            88           88                      0.75               75.21%
10                   Cited Resource Identifier  GeoTraces_ISO             2            2                      0.02                1.71%
11                        Cited Resource Title  GeoTraces_ISO          1700          117                     14.53              100.00%
12                                        City  GeoTraces_ISO           591          117                      5.05              100.00%
13                        Contact Instructions  GeoTraces_ISO           468          117                      4.00              100.00%
14                                     Country  GeoTraces_ISO           579          117                      4.95              100.00%
15                          Data Quality Scope  GeoTraces_ISO           117          117                      1.00              100.00%
16                                    DataType  GeoTraces_ISO          1954          117                     16.70              100.00%
17                              DimensionsName  GeoTraces_ISO          4385          117                     37.48              100.00%
18                        Distribution Contact  GeoTraces_ISO           117          117                      1.00              100.00%
19                       Easternmost Longitude  GeoTraces_ISO            88           88                      0.75               75.21%
20                                       Email  GeoTraces_ISO           589          117                      5.03              100.00%
21                                    End Time  GeoTraces_ISO             9            9                      0.08                7.69%
22   Enumerated Domain Value Definition Source  GeoTraces_ISO           571          117                      4.88              100.00%
23                                         Fax  GeoTraces_ISO           468          117                      4.00              100.00%
24                  Feature Catalogue Citation  GeoTraces_ISO           234          117                      2.00              100.00%
25                                  First Name  GeoTraces_ISO           408          117                      3.49              100.00%
26                      Geographic Description  GeoTraces_ISO           117          117                      1.00              100.00%
27                            Hours of Service  GeoTraces_ISO           468          117                      4.00              100.00%
28                                  Instrument  GeoTraces_ISO           268          103                      2.29               88.03%
29                          Instrument Keyword  GeoTraces_ISO           268          103                      2.29               88.03%
..                                         ...            ...           ...          ...                       ...                  ...
73                 Related Resource Identifier  GeoTraces_ISO           667          117                      5.70              100.00%
74                      Reprocessing Plan Note  GeoTraces_ISO           117          117                      1.00              100.00%
75                 Resource Access Constraints  GeoTraces_ISO           234          117                      2.00              100.00%
76                            Resource Contact  GeoTraces_ISO           125          117                      1.07              100.00%
77             Resource Creation/Revision Date  GeoTraces_ISO           117          117                      1.00              100.00%
78                         Resource Identifier  GeoTraces_ISO             2            2                      0.02                1.71%
79                           Resource Language  GeoTraces_ISO           117          117                      1.00              100.00%
80                            Resource Lineage  GeoTraces_ISO           117          117                      1.00              100.00%
81                          Resource Long Name  GeoTraces_ISO           117          117                      1.00              100.00%
82                             Resource Status  GeoTraces_ISO           117          117                      1.00              100.00%
83                              Resource Title  GeoTraces_ISO           117          117                      1.00              100.00%
84                               Resource Type  GeoTraces_ISO           117          117                      1.00              100.00%
85                   Resource Update Frequency  GeoTraces_ISO           117          117                      1.00              100.00%
86                    Resource Use Constraints  GeoTraces_ISO           117          117                      1.00              100.00%
87                              Responsibility  GeoTraces_ISO          1962          117                     16.77              100.00%
88                                      Rights  GeoTraces_ISO           117          117                      1.00              100.00%
89                                        Role  GeoTraces_ISO           819          117                      7.00              100.00%
90                       Southernmost Latitude  GeoTraces_ISO            88           88                      0.75               75.21%
91                              Spatial Extent  GeoTraces_ISO            88           88                      0.75               75.21%
92                    Standard Name Vocabulary  GeoTraces_ISO           571          117                      4.88              100.00%
93                                  Start Time  GeoTraces_ISO             9            9                      0.08                7.69%
94                             Temporal Extent  GeoTraces_ISO           117          117                      1.00              100.00%
95                               Theme Keyword  GeoTraces_ISO          3106          117                     26.55              100.00%
96                              Topic Category  GeoTraces_ISO           118          117                      1.01              100.00%
97                                         URL  GeoTraces_ISO           116          116                      0.99               99.15%
98                                       Units  GeoTraces_ISO          4385          117                     37.48              100.00%
99                                     Unknown  GeoTraces_ISO         73002          117                    623.95              100.00%
100                               VariableType  GeoTraces_ISO           117          117                      1.00              100.00%
101                                   Web Page  GeoTraces_ISO           887          117                      7.58              100.00%
102                      Westernmost Longitude  GeoTraces_ISO            88           88                      0.75               75.21%

[103 rows x 6 columns]

### Select the notebook that prepares the data for different types of analysis

* [Create RAD Data](02RADdf.ipynb)
* [Cross Collection Comparisons](03CrossCollectionComparisons.ipynb)
* [Concept Content Consistency](04ConceptVerticals.ipynb)
* [Exploring Unknown Concepts](05ExploringUnknownConcepts.ipynb)